# This is just a sample file. For a fully documented version of this file, see
# https://github.com/galaxyproject/ansible-galaxy-tools/blob/master/files/tool_list.yaml.sample
api_key: fakekey
galaxy_instance: http://localhost:8080
install_repository_dependencies: False
install_resolver_dependencies: True
install_tool_dependencies: True
tools:

## UPLOAD DATA

- name: sra_tools
  owner: iuc
  tool_panel_section_id: 'getdb'
  tool_shed_url: https://toolshed.g2.bx.psu.edu

- name: fetch_fasta_from_ncbi
  owner: artbio
  tool_panel_section_id: 'getdb'
  tool_shed_url: https://toolshed.g2.bx.psu.edu
  
#####################
#####################
#####################

########### BLAST

- name: ncbi_blast_plus
  owner: devteam
  tool_panel_section_id: 'blast'
  
- name: blast2go
  owner: peterjc
  tool_panel_section_id: 'blast'
  
- name: 'diamond'
  owner: 'bgruening'
  tool_panel_section_id: 'blast'
  
- name: megablast_xml_parser
  owner: devteam
  tool_panel_section_id: 'blast'

- name: megablast_wrapper
  owner: devteam
  tool_panel_section_id: 'blast'
  
- name: blast_parser
  owner: earlhaminst
  tool_panel_section_id: 'blast'
  
- name: blast_rbh
  owner: peterjc
  tool_panel_section_id: 'blast'

- name: blast_rbh
  owner: peterjc
  tool_panel_section_id: 'blast'
  
#####################
#####################
#####################

########### SIMILARITY

- name: mafft
  owner: rnateam
  tool_panel_section_id: 'similarity'

- name: clustalw
  owner: devteam
  tool_panel_section_id: 'similarity'
  
- name: muscle
  owner: crs4
  tool_panel_section_id: 'similarity'

- name: 'cdhit'
  owner: 'bebatut'
  tool_panel_section_id: 'similarity'

- name: 'format_cd_hit_output'
  owner: 'bebatut'
  tool_panel_section_id: 'similarity'

#####################
#####################
#####################

########### PHYLOGENY TOOLS
  
- name: fasttree
  owner: iuc
  tool_panel_section_id: 'taxon'

- name: phyml
  owner: vlefort
  tool_panel_section_id: 'taxon'

- name: raxml
  owner: iuc
  tool_panel_section_id: 'taxon'
  
- name: taxonomy_krona_chart
  owner: crs4
  tool_panel_section_id: 'taxon'

- name: kraken2
  owner: iuc
  tool_panel_section_id: 'taxon'

- name: kraken_taxonomy_report
  owner: iuc
  tool_panel_section_id: 'taxon'

- name: kraken2tax
  owner: devteam
  tool_panel_section_id: 'taxon'

- name: kraken
  owner: devteam
  tool_panel_section_id: 'taxon'

- name: kraken_report
  owner: devteam
  tool_panel_section_id: 'taxon'

- name: kraken_filter
  owner: devteam
  tool_panel_section_id: 'taxon'

- name: kraken_translate
  owner: devteam
  tool_panel_section_id: 'taxon'
  
- name: hcluster_sg
  owner: earlhaminst
  tool_panel_section_id: 'taxon'

- name: hcluster_sg_parser
  owner: earlhaminst 
  tool_panel_section_id: 'taxon'

- name: t_coffee
  owner: earlhaminst
  tool_panel_section_id: 'taxon'

- name: treebest_best
  owner: earlhaminst
  tool_panel_section_id: 'taxon'

- name: gafa
  owner: earlhaminst
  tool_panel_section_id: 'taxon'
    
- name: gstf_preparation
  owner: earlhaminst
  tool_panel_section_id: 'taxon'
   
- name: ete
  owner: earlhaminst
  tool_panel_section_id: 'taxon'
