# This is just a sample file. For a fully documented version of this file, see
# https://github.com/galaxyproject/ansible-galaxy-tools/blob/master/files/tool_list.yaml.sample
api_key: fakekey
galaxy_instance: http://localhost:8080
install_repository_dependencies: False
install_resolver_dependencies: True
install_tool_dependencies: True
tools:

########### DATA MANAGER
- name: data_manager_sam_fasta_index_builder
  owner: devteam
  revisions:
    - '1865e693d8b2'

- name: data_manager_fetch_busco
  owner: iuc

- name: data_manager_picard_index_builder
  owner: devteam

- name: data_manager_gatk_picard_index_builder
  owner: devteam

- name: data_manager_bowtie2_index_builder
  owner: devteam

- name: data_manager_bwa_mem_index_builder
  owner: devteam

- name: data_manager_star_index_builder
  owner: iuc
  revisions:
    - '64deddb6a8ec'

- name: data_manager_hisat2_index_builder
  owner: iuc

- name: data_manager_salmon_index_builder
  owner: ieguinoa

- name: data_manager_kallisto_index_builder
  owner: iuc

- name: data_manager_build_kraken_database
  owner: devteam

- name: data_manager_bowtie_index_builder
  owner: iuc

- name: data_manager_diamond_database_builder
  owner: bgruening
  
- name: data_manager_fetch_refseq
  owner: iuc
  
- name: data_manager_fetch_ncbi_taxonomy
  owner: devteam
  
- name: data_manager_fetch_tx2gene
  owner: ieguinoa
  
- name: data_manager_for_directory_data
  owner: brenninc
  
- name: data_manager_humann2_database_downloader
  owner: iuc
  
- name: data_manager_metaphlan2_database_downloader
  owner: iuc
  
- name: data_manager_ncbi_taxonomy_sqlite
  owner: iuc
  
- name: data_manager_rsync_g2
  owner: devteam
  
- name: data_manager_select_index_by_path
  owner: rhpvorderman
  
- name: data_manager_sortmerna_database_downloader
  owner: rnateam
  
- name: data_manager_qiime_database_downloader
  owner: iuc
  
- name: data_manager_mothur_toolsuite
  owner: iuc

###################
#####################
#####################
