# This is just a sample file. For a fully documented version of this file, see
# https://github.com/galaxyproject/ansible-galaxy-tools/blob/master/files/tool_list.yaml.sample
api_key: fakekey
galaxy_instance: http://localhost:8080
install_repository_dependencies: False
install_resolver_dependencies: True
install_tool_dependencies: True
tools:
  
#####################
#####################
#####################

###### R PACKAGES
  
- name: deseq2
  owner: iuc
  tool_panel_section_id: 'rlang'
  
- name: deseq2_normalization
  owner: artbio
  tool_panel_section_id: 'rlang'
  
- name: edger
  owner: iuc
  tool_panel_section_id: 'rlang'
  
- name: plotheatmap
  owner: earlhaminst
  tool_panel_section_id: 'rlang'
  
- name: shrnaseq
  owner: shians
  tool_panel_section_id: 'rlang'
  
- name: dexseq
  owner: iuc
  tool_panel_section_id: 'rlang'
  
- name: ebseq_eba
  owner: yboursin
  tool_panel_section_id: 'rlang'
  tool_shed_url: https://testtoolshed.g2.bx.psu.edu/
  
- name: pre_ebseq_eba
  owner: yboursin
  tool_panel_section_id: 'rlang'
  tool_shed_url: https://testtoolshed.g2.bx.psu.edu/

- name: cummerbund
  owner: devteam
  tool_panel_section_id: 'tuxedo'
  
- name: package_cummerbund_2_8_2
  owner: iuc
  tool_panel_section_id: 'tuxedo'
  
- name: cummerbund_to_tabular
  owner: devteam
  tool_panel_section_id: 'tuxedo'
